using Example01.Data;
// In environments such as ASP.NET, you probably wouldn't instantiate the instance od DbContext manually.
PostgresContext _context = new();

var solutions = _context.StudentSolutions.Where(s => s.PointsGraded != null).OrderByDescending(s => s.SubmittedAt);
// This statement can be translated to: 
//      SELECT * FROM student_solution s WHERE s.points_graded IS NOT NULL ORDER BY submitted_at DESC 

foreach (StudentSolution solution in solutions)
{
    Console.WriteLine(
        $"solution (id={solution.Id}) for schoolwork={solution.SchoolworkId} - {solution.PointsGraded} pts - submitted at: {solution.SubmittedAt}");
}

// To create new student, first create a student object.
Student student = new()
{
    FirstName = "Yugi", LastName = "Muto", Jmbag = "0000000101234" 
};

// This object is not tracked, therefore it will not be saved in the database. One option to start tracking the object is to add it to DbSet<T> explicitly.
_context.Students.Add(student);

// Student id is set to 0 (by default), actuall value will be generated by the database after the insert.
Console.WriteLine($"student id before the change is commited: {student.Id}");
// Then call SaveChanges which will group all of the operations on current session's tracked objects into a single transactional context and execute it.
_context.SaveChanges();

Console.WriteLine($"student id after the change is commited: {student.Id}");

// Inspect the content of the "student" table before and after running the program
